#include <bits/stdc++.h>
using namespace std;using Clock=chrono::steady_clock;int b[15][15],me,nodes;Clock::time_point stop;unordered_map<unsigned long long,unsigned char> tt;
int ds[4][2]={{1,0},{0,1},{1,1},{1,-1}};bool I(int r,int c){return r>=0&&r<15&&c>=0&&c<15;}
int run(int r,int c,int dr,int dc,int p){int n=1;for(int k=1;;k++){int x=r+k*dr,y=c+k*dc;if(I(x,y)&&b[x][y]==p)n++;else break;}for(int k=1;;k++){int x=r-k*dr,y=c-k*dc;if(I(x,y)&&b[x][y]==p)n++;else break;}return n;}
bool win(int r,int c,int p){for(auto&q:ds)if(run(r,c,q[0],q[1],p)==5)return 1;return 0;}
int four(int r,int c,int dr,int dc){int a=0,m=1,z=0;bool g=0;for(int k=-1;;k--){int x=r+k*dr,y=c+k*dc;if(!I(x,y)){if(!g)a=-1;break;}int v=b[x][y];if(v==1){if(!g)a=-1;break;}if(v==0){if(g)a++;else m++;}else{if(g)break;g=1;}}g=0;for(int k=1;;k++){int x=r+k*dr,y=c+k*dc;if(!I(x,y)){if(!g)z=-1;break;}int v=b[x][y];if(v==1){if(!g)z=-1;break;}if(v==0){if(g)z++;else m++;}else{if(g)break;g=1;}}if(m==4)return a==0||z==0;return (a>0&&a+m==4)+(z>0&&m+z==4);}
bool legal(int r,int c,int p){if(!I(r,c)||b[r][c]!=-1)return 0;if(p){return 1;}b[r][c]=p;int f=0;for(auto&q:ds)f+=four(r,c,q[0],q[1]);bool x=f>1;for(auto&q:ds)x|=run(r,c,q[0],q[1],p)>5;b[r][c]=-1;return !x;}
int score(int r,int c,int p){b[r][c]=p;int s=win(r,c,p)?1000000:0;for(auto&q:ds){int n=run(r,c,q[0],q[1],p);s+=(n==4?10000:n==3?600:n==2?30:2*n);}b[r][c]=-1;return s;}
vector<pair<int,int>> cand(int p,bool forcing){vector<tuple<int,int,int>>v;for(int r=0;r<15;r++)for(int c=0;c<15;c++)if(legal(r,c,p)){bool near=0;for(int x=-2;x<=2;x++)for(int y=-2;y<=2;y++)if(I(r+x,c+y)&&b[r+x][c+y]!=-1)near=1;if(near||forcing)v.push_back({-score(r,c,p),r,c});}sort(v.begin(),v.end());vector<pair<int,int>>o;for(auto&t:v)if(o.size()< (forcing?20:12))o.push_back({get<1>(t),get<2>(t)});return o;}
bool force(int p,int depth){if(Clock::now()>=stop||nodes++>45000)return false;if(depth<=0)return false;auto a=cand(p,true);for(auto q:a){b[q.first][q.second]=p;bool w=win(q.first,q.second,p);b[q.first][q.second]=-1;if(w)return true;}for(auto q:a){b[q.first][q.second]=p;vector<pair<int,int>> resp;for(auto z:cand(p^1,true)){b[z.first][z.second]=p^1;if(win(z.first,z.second,p^1))resp.push_back(z);b[z.first][z.second]=-1;}b[q.first][q.second]=-1;if(resp.empty())continue;bool all=1;for(auto z:resp){b[z.first][z.second]=p^1;all&=force(p,depth-1);b[z.first][z.second]=-1;if(!all)break;}if(all)return true;}return false;}
int main(){ios::sync_with_stdio(0);cin.tie(0);if(!(cin>>me))return 0;for(auto&r:b)for(int&x:r){cin>>x;if(x!=0&&x!=1)x=-1;}auto all=cand(me,false);if(all.empty())all={{7,7}};for(auto q:all){if(!legal(q.first,q.second,me))continue;b[q.first][q.second]=me;bool w=win(q.first,q.second,me);b[q.first][q.second]=-1;if(w){cout<<q.first<<' '<<q.second;return 0;}}for(int r=0;r<15;r++)for(int c=0;c<15;c++)if(legal(r,c,me^1)){b[r][c]=me^1;bool w=win(r,c,me^1);b[r][c]=-1;if(w&&legal(r,c,me)){cout<<r<<' '<<c;return 0;}}stop=Clock::now()+chrono::milliseconds(520);for(auto q:all){b[q.first][q.second]=me;nodes=0;bool w=force(me,4);b[q.first][q.second]=-1;if(w){cout<<q.first<<' '<<q.second;return 0;}}cout<<all.front().first<<' '<<all.front().second;}
