#include <bits/stdc++.h>
using namespace std; const int N=15; using B=array<array<int,N>,N>; struct M{int r,c;};
bool I(int r,int c){return r>=0&&r<N&&c>=0&&c<N;} int L(const B&b,int r,int c,int dr,int dc,int p){int n=1;for(int s:{-1,1}){int x=r+dr*s,y=c+dc*s;while(I(x,y)&&b[x][y]==p)n++,x+=dr*s,y+=dc*s;}return n;} bool W(const B&b,M m,int p){for(auto d:array<pair<int,int>,4>{{{1,0},{0,1},{1,1},{1,-1}}})if(L(b,m.r,m.c,d.first,d.second,p)>=5)return 1;return 0;}
bool foul(const B&b,M m){if(b[m.r][m.c]>=0)return 1;B q=b;q[m.r][m.c]=0;int f=0,t=0;for(auto d:array<pair<int,int>,4>{{{1,0},{0,1},{1,1},{1,-1}}}){int n=L(q,m.r,m.c,d.first,d.second,0);if(n>5)return 1;if(n>=4)f++;if(n==3){int a=0;for(int s:{-1,1}){int x=m.r+s*d.first,y=m.c+s*d.second;if(I(x,y)&&q[x][y]<0)a++;}if(a==2)t++;}}return f>1||t>1;}
vector<M> gen(const B&b,int p){vector<M>v;bool any=0;for(auto&r:b)for(int x:r)any|=x>=0;if(!any)return{{7,7}};for(int r=0;r<N;r++)for(int c=0;c<N;c++)if(b[r][c]<0&&!(p==0&&foul(b,{r,c}))){bool n=0;for(int i=max(0,r-2);i<=min(14,r+2);i++)for(int j=max(0,c-2);j<=min(14,c+2);j++)n|=b[i][j]>=0;if(n)v.push_back({r,c});}return v;}
int pat(const B&b,M m,int p){B q=b;q[m.r][m.c]=p;int s=0;for(auto d:array<pair<int,int>,4>{{{1,0},{0,1},{1,1},{1,-1}}}){int n=L(q,m.r,m.c,d.first,d.second,p);s+=n>=5?100000:n==4?5000:n==3?350:n==2?25:1;}return s;}
struct Node{B b;int score;};
int main(){ios::sync_with_stdio(false);cin.tie(nullptr);int me;if(!(cin>>me))return 0;B b;for(auto&r:b)for(int&x:r)cin>>x;int op=1-me;auto root=gen(b,me);for(M m:root){B q=b;q[m.r][m.c]=me;if(W(q,m,me)){cout<<m.r<<' '<<m.c;return 0;}}for(M m:root){B q=b;q[m.r][m.c]=op;if(W(q,m,op)){cout<<m.r<<' '<<m.c;return 0;}}
 vector<Node> beam;for(M m:root){B q=b;q[m.r][m.c]=me;beam.push_back({q,pat(q,m,me)*2-pat(q,m,op)});}const int width=12;for(int depth=1;depth<5;depth++){vector<Node> nxt;int turn=(depth&1)?op:me;for(auto&n:beam){auto v=gen(n.b,turn);for(M m:v){B q=n.b;q[m.r][m.c]=turn;int z=n.score+(turn==me?pat(q,m,me)*2-pat(q,m,op):pat(q,m,me)-pat(q,m,op)*2);nxt.push_back({q,z});}}sort(nxt.begin(),nxt.end(),[](const Node&a,const Node&b){return a.score>b.score;});if(nxt.size()>width)nxt.resize(width);beam.swap(nxt);}
 int best=-1,bs=INT_MIN;for(M m:root){B q=b;q[m.r][m.c]=me;int s=pat(q,m,me)*2-pat(q,m,op);for(auto&n:beam)if(n.b[m.r][m.c]==me)s=max(s,n.score);if(s>bs)bs=s,best=m.r*N+m.c;}if(best<0)best=7*N+7;cout<<best/N<<' '<<best%N<<'\n';}
