#include <bits/stdc++.h>
using namespace std; int b[15][15],me,nodes; int d[4][2]={{1,0},{0,1},{1,1},{1,-1}};
bool in(int r,int c){return r>=0&&r<15&&c>=0&&c<15;} int run(int r,int c,int a,int z,int p){int n=0;for(int k=-4;k<=4;k++){int x=r+k*a,y=c+k*z;if(in(x,y)&&b[x][y]==p)n++;else if(k>=0&&n)break;}return n;}
bool win(int r,int c,int p){for(auto &q:d)if(run(r,c,q[0],q[1],p)>=5)return 1;return 0;}
int four(int r,int c,int dr,int dc){int before=0,middle=1,after=0;bool gap=0;for(int s=-1;;s--){int x=r+s*dr,y=c+s*dc;if(!in(x,y)){if(!gap)before=-1;break;}int v=b[x][y];if(v==1){if(!gap)before=-1;break;}if(v==0){if(gap)before++;else middle++;}else{if(gap)break;gap=1;}}gap=0;for(int s=1;;s++){int x=r+s*dr,y=c+s*dc;if(!in(x,y)){if(!gap)after=-1;break;}int v=b[x][y];if(v==1){if(!gap)after=-1;break;}if(v==0){if(gap)after++;else middle++;}else{if(gap)break;gap=1;}}if(middle==4)return (before==0||after==0);return (before>0&&before+middle==4)+(after>0&&middle+after==4);}
bool ok(int r,int c,int p){if(!in(r,c)||b[r][c]!=-1)return 0;if(p!=0)return 1;b[r][c]=p;bool bad=0;int fc=0;for(auto&q:d){if(run(r,c,q[0],q[1],p)>5)bad=1;fc+=four(r,c,q[0],q[1]);}b[r][c]=-1;return !bad&&fc<=1;}
int val(int r,int c,int p){b[r][c]=p;int s=win(r,c,p)?100000:0;for(auto&q:d){int n=run(r,c,q[0],q[1],p);s+=(n==4?4000:n==3?250:n==2?20:n*2);}b[r][c]=-1;return s;}
vector<pair<int,int>> gen(int p){vector<tuple<int,int,int>>v;bool empty=1;for(auto&r:b)for(int x:r)if(x!=-1)empty=0;if(empty)return{{7,7}};for(int r=0;r<15;r++)for(int c=0;c<15;c++)if(ok(r,c,p)){bool near=0;for(int x=-2;x<=2;x++)for(int y=-2;y<=2;y++)if(in(r+x,c+y)&&b[r+x][c+y]!=-1)near=1;if(near)v.push_back({-val(r,c,p)-val(r,c,p^1)/3,r,c});}sort(v.begin(),v.end());vector<pair<int,int>>o;for(int i=0;i<(int)v.size()&&i<14;i++)o.push_back({get<1>(v[i]),get<2>(v[i])});return o;}
int ab(int p,int dep,int al,int be){if(++nodes>50000)return 0;if(!dep)return 0;int best=-1e9;for(auto q:gen(p)){b[q.first][q.second]=p;int s=win(q.first,q.second,p)?900000:-ab(p^1,dep-1,-be,-al);b[q.first][q.second]=-1;best=max(best,s);al=max(al,s);if(al>=be)break;}return best;}
int main(){ios::sync_with_stdio(0);cin.tie(0);if(!(cin>>me))return 0;for(auto&r:b)for(int&x:r){cin>>x;if(x!=0&&x!=1)x=-1;}auto v=gen(me);pair<int,int>a=v.front();int best=-1e9;
// Root hard constraints: take an immediate win, otherwise block every legal opponent win.
for(auto q:v){if(ok(q.first,q.second,me)){b[q.first][q.second]=me;bool w=win(q.first,q.second,me);b[q.first][q.second]=-1;if(w){cout<<q.first<<" "<<q.second<<"\n";return 0;}}}
for(auto q:v){if(!ok(q.first,q.second,me))continue;b[q.first][q.second]=me;int s=0;for(int r=0;r<15;r++)for(int c=0;c<15;c++)if(ok(r,c,me^1)){b[r][c]=me^1;bool w=win(r,c,me^1);b[r][c]=-1;if(w)s=-800000;}s=s?:-ab(me^1,2,-1e9,1e9);b[q.first][q.second]=-1;if(s>best)best=s,a=q;}cout<<a.first<<" "<<a.second<<"\n";}
